// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: misc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageOrigin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageOrigin) Reset() {
	*x = MessageOrigin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOrigin) ProtoMessage() {}

func (x *MessageOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOrigin.ProtoReflect.Descriptor instead.
func (*MessageOrigin) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{0}
}

type ExternalReplyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExternalReplyInfo) Reset() {
	*x = ExternalReplyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalReplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalReplyInfo) ProtoMessage() {}

func (x *ExternalReplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalReplyInfo.ProtoReflect.Descriptor instead.
func (*ExternalReplyInfo) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{1}
}

type TextQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TextQuote) Reset() {
	*x = TextQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextQuote) ProtoMessage() {}

func (x *TextQuote) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextQuote.ProtoReflect.Descriptor instead.
func (*TextQuote) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{2}
}

type Story struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Story) Reset() {
	*x = Story{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{3}
}

type Animation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Animation) Reset() {
	*x = Animation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Animation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animation) ProtoMessage() {}

func (x *Animation) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animation.ProtoReflect.Descriptor instead.
func (*Animation) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{4}
}

type Audio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Audio) Reset() {
	*x = Audio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{5}
}

type PaidMediaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaidMediaInfo) Reset() {
	*x = PaidMediaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaidMediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaidMediaInfo) ProtoMessage() {}

func (x *PaidMediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaidMediaInfo.ProtoReflect.Descriptor instead.
func (*PaidMediaInfo) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{6}
}

type Sticker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sticker) Reset() {
	*x = Sticker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sticker) ProtoMessage() {}

func (x *Sticker) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sticker.ProtoReflect.Descriptor instead.
func (*Sticker) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{7}
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{8}
}

type VideoNote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoNote) Reset() {
	*x = VideoNote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoNote) ProtoMessage() {}

func (x *VideoNote) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoNote.ProtoReflect.Descriptor instead.
func (*VideoNote) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{9}
}

type Voice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Voice) Reset() {
	*x = Voice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voice) ProtoMessage() {}

func (x *Voice) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voice.ProtoReflect.Descriptor instead.
func (*Voice) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{10}
}

type MessageEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageEntity) Reset() {
	*x = MessageEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEntity) ProtoMessage() {}

func (x *MessageEntity) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEntity.ProtoReflect.Descriptor instead.
func (*MessageEntity) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{11}
}

type LinkPreviewOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LinkPreviewOptions) Reset() {
	*x = LinkPreviewOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkPreviewOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPreviewOptions) ProtoMessage() {}

func (x *LinkPreviewOptions) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPreviewOptions.ProtoReflect.Descriptor instead.
func (*LinkPreviewOptions) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{12}
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{13}
}

type Dice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Dice) Reset() {
	*x = Dice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dice) ProtoMessage() {}

func (x *Dice) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dice.ProtoReflect.Descriptor instead.
func (*Dice) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{14}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{15}
}

type Poll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Poll) Reset() {
	*x = Poll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{16}
}

type Venue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Venue) Reset() {
	*x = Venue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Venue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue) ProtoMessage() {}

func (x *Venue) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue.ProtoReflect.Descriptor instead.
func (*Venue) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{17}
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{18}
}

type MaybeInaccessibleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MaybeInaccessibleMessage) Reset() {
	*x = MaybeInaccessibleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaybeInaccessibleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaybeInaccessibleMessage) ProtoMessage() {}

func (x *MaybeInaccessibleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaybeInaccessibleMessage.ProtoReflect.Descriptor instead.
func (*MaybeInaccessibleMessage) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{19}
}

type Invoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{20}
}

type SuccessfulPayment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SuccessfulPayment) Reset() {
	*x = SuccessfulPayment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessfulPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulPayment) ProtoMessage() {}

func (x *SuccessfulPayment) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulPayment.ProtoReflect.Descriptor instead.
func (*SuccessfulPayment) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{21}
}

type RefundedPayment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefundedPayment) Reset() {
	*x = RefundedPayment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundedPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundedPayment) ProtoMessage() {}

func (x *RefundedPayment) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundedPayment.ProtoReflect.Descriptor instead.
func (*RefundedPayment) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{22}
}

type UsersShared struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UsersShared) Reset() {
	*x = UsersShared{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersShared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersShared) ProtoMessage() {}

func (x *UsersShared) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersShared.ProtoReflect.Descriptor instead.
func (*UsersShared) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{23}
}

type ChatShared struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatShared) Reset() {
	*x = ChatShared{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatShared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatShared) ProtoMessage() {}

func (x *ChatShared) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatShared.ProtoReflect.Descriptor instead.
func (*ChatShared) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{24}
}

type WriteAccessAllowed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WriteAccessAllowed) Reset() {
	*x = WriteAccessAllowed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteAccessAllowed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAccessAllowed) ProtoMessage() {}

func (x *WriteAccessAllowed) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAccessAllowed.ProtoReflect.Descriptor instead.
func (*WriteAccessAllowed) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{25}
}

type PassportData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PassportData) Reset() {
	*x = PassportData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassportData) ProtoMessage() {}

func (x *PassportData) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassportData.ProtoReflect.Descriptor instead.
func (*PassportData) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{26}
}

type ProximityAlertTriggered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProximityAlertTriggered) Reset() {
	*x = ProximityAlertTriggered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProximityAlertTriggered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProximityAlertTriggered) ProtoMessage() {}

func (x *ProximityAlertTriggered) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProximityAlertTriggered.ProtoReflect.Descriptor instead.
func (*ProximityAlertTriggered) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{27}
}

type ChatBoostAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatBoostAdded) Reset() {
	*x = ChatBoostAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatBoostAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBoostAdded) ProtoMessage() {}

func (x *ChatBoostAdded) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBoostAdded.ProtoReflect.Descriptor instead.
func (*ChatBoostAdded) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{28}
}

type ChatBackground struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatBackground) Reset() {
	*x = ChatBackground{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatBackground) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBackground) ProtoMessage() {}

func (x *ChatBackground) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBackground.ProtoReflect.Descriptor instead.
func (*ChatBackground) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{29}
}

type ForumTopicCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForumTopicCreated) Reset() {
	*x = ForumTopicCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForumTopicCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForumTopicCreated) ProtoMessage() {}

func (x *ForumTopicCreated) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForumTopicCreated.ProtoReflect.Descriptor instead.
func (*ForumTopicCreated) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{30}
}

type ForumTopicEdited struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForumTopicEdited) Reset() {
	*x = ForumTopicEdited{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForumTopicEdited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForumTopicEdited) ProtoMessage() {}

func (x *ForumTopicEdited) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForumTopicEdited.ProtoReflect.Descriptor instead.
func (*ForumTopicEdited) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{31}
}

type ForumTopicClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForumTopicClosed) Reset() {
	*x = ForumTopicClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForumTopicClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForumTopicClosed) ProtoMessage() {}

func (x *ForumTopicClosed) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForumTopicClosed.ProtoReflect.Descriptor instead.
func (*ForumTopicClosed) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{32}
}

type ForumTopicReopened struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForumTopicReopened) Reset() {
	*x = ForumTopicReopened{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForumTopicReopened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForumTopicReopened) ProtoMessage() {}

func (x *ForumTopicReopened) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForumTopicReopened.ProtoReflect.Descriptor instead.
func (*ForumTopicReopened) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{33}
}

type GeneralForumTopicHidden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GeneralForumTopicHidden) Reset() {
	*x = GeneralForumTopicHidden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralForumTopicHidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralForumTopicHidden) ProtoMessage() {}

func (x *GeneralForumTopicHidden) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralForumTopicHidden.ProtoReflect.Descriptor instead.
func (*GeneralForumTopicHidden) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{34}
}

type GeneralForumTopicUnhidden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GeneralForumTopicUnhidden) Reset() {
	*x = GeneralForumTopicUnhidden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralForumTopicUnhidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralForumTopicUnhidden) ProtoMessage() {}

func (x *GeneralForumTopicUnhidden) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralForumTopicUnhidden.ProtoReflect.Descriptor instead.
func (*GeneralForumTopicUnhidden) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{35}
}

type GiveawayCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GiveawayCreated) Reset() {
	*x = GiveawayCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveawayCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveawayCreated) ProtoMessage() {}

func (x *GiveawayCreated) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveawayCreated.ProtoReflect.Descriptor instead.
func (*GiveawayCreated) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{36}
}

type Giveaway struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Giveaway) Reset() {
	*x = Giveaway{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Giveaway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Giveaway) ProtoMessage() {}

func (x *Giveaway) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Giveaway.ProtoReflect.Descriptor instead.
func (*Giveaway) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{37}
}

type GiveawayWinners struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GiveawayWinners) Reset() {
	*x = GiveawayWinners{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveawayWinners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveawayWinners) ProtoMessage() {}

func (x *GiveawayWinners) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveawayWinners.ProtoReflect.Descriptor instead.
func (*GiveawayWinners) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{38}
}

type GiveawayCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GiveawayCompleted) Reset() {
	*x = GiveawayCompleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveawayCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveawayCompleted) ProtoMessage() {}

func (x *GiveawayCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveawayCompleted.ProtoReflect.Descriptor instead.
func (*GiveawayCompleted) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{39}
}

type VideoChatScheduled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoChatScheduled) Reset() {
	*x = VideoChatScheduled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoChatScheduled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChatScheduled) ProtoMessage() {}

func (x *VideoChatScheduled) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChatScheduled.ProtoReflect.Descriptor instead.
func (*VideoChatScheduled) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{40}
}

type VideoChatStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoChatStarted) Reset() {
	*x = VideoChatStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoChatStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChatStarted) ProtoMessage() {}

func (x *VideoChatStarted) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChatStarted.ProtoReflect.Descriptor instead.
func (*VideoChatStarted) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{41}
}

type VideoChatEnded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoChatEnded) Reset() {
	*x = VideoChatEnded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[42]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoChatEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChatEnded) ProtoMessage() {}

func (x *VideoChatEnded) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[42]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChatEnded.ProtoReflect.Descriptor instead.
func (*VideoChatEnded) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{42}
}

type VideoChatParticipantsInvited struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoChatParticipantsInvited) Reset() {
	*x = VideoChatParticipantsInvited{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[43]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoChatParticipantsInvited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChatParticipantsInvited) ProtoMessage() {}

func (x *VideoChatParticipantsInvited) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[43]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChatParticipantsInvited.ProtoReflect.Descriptor instead.
func (*VideoChatParticipantsInvited) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{43}
}

type WebAppData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebAppData) Reset() {
	*x = WebAppData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[44]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebAppData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAppData) ProtoMessage() {}

func (x *WebAppData) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[44]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAppData.ProtoReflect.Descriptor instead.
func (*WebAppData) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{44}
}

type MessageAutoDeleteTimerChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageAutoDeleteTimerChanged) Reset() {
	*x = MessageAutoDeleteTimerChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[45]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageAutoDeleteTimerChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAutoDeleteTimerChanged) ProtoMessage() {}

func (x *MessageAutoDeleteTimerChanged) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[45]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAutoDeleteTimerChanged.ProtoReflect.Descriptor instead.
func (*MessageAutoDeleteTimerChanged) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{45}
}

type BusinessConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BusinessConnection) Reset() {
	*x = BusinessConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[46]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessConnection) ProtoMessage() {}

func (x *BusinessConnection) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[46]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessConnection.ProtoReflect.Descriptor instead.
func (*BusinessConnection) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{46}
}

type BusinessMessagesDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BusinessMessagesDeleted) Reset() {
	*x = BusinessMessagesDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[47]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessMessagesDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessMessagesDeleted) ProtoMessage() {}

func (x *BusinessMessagesDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[47]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessMessagesDeleted.ProtoReflect.Descriptor instead.
func (*BusinessMessagesDeleted) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{47}
}

type MessageReactionUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageReactionUpdated) Reset() {
	*x = MessageReactionUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[48]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageReactionUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReactionUpdated) ProtoMessage() {}

func (x *MessageReactionUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[48]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReactionUpdated.ProtoReflect.Descriptor instead.
func (*MessageReactionUpdated) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{48}
}

type MessageReactionCountUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageReactionCountUpdated) Reset() {
	*x = MessageReactionCountUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[49]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageReactionCountUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReactionCountUpdated) ProtoMessage() {}

func (x *MessageReactionCountUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[49]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReactionCountUpdated.ProtoReflect.Descriptor instead.
func (*MessageReactionCountUpdated) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{49}
}

type InlineQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InlineQuery) Reset() {
	*x = InlineQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[50]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InlineQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineQuery) ProtoMessage() {}

func (x *InlineQuery) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[50]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineQuery.ProtoReflect.Descriptor instead.
func (*InlineQuery) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{50}
}

type ChosenInlineResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChosenInlineResult) Reset() {
	*x = ChosenInlineResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[51]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChosenInlineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChosenInlineResult) ProtoMessage() {}

func (x *ChosenInlineResult) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[51]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChosenInlineResult.ProtoReflect.Descriptor instead.
func (*ChosenInlineResult) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{51}
}

type CallbackQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CallbackQuery) Reset() {
	*x = CallbackQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[52]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackQuery) ProtoMessage() {}

func (x *CallbackQuery) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[52]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackQuery.ProtoReflect.Descriptor instead.
func (*CallbackQuery) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{52}
}

type ShippingQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShippingQuery) Reset() {
	*x = ShippingQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[53]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShippingQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingQuery) ProtoMessage() {}

func (x *ShippingQuery) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[53]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingQuery.ProtoReflect.Descriptor instead.
func (*ShippingQuery) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{53}
}

type PreCheckoutQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PreCheckoutQuery) Reset() {
	*x = PreCheckoutQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[54]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreCheckoutQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckoutQuery) ProtoMessage() {}

func (x *PreCheckoutQuery) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[54]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckoutQuery.ProtoReflect.Descriptor instead.
func (*PreCheckoutQuery) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{54}
}

type PollAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PollAnswer) Reset() {
	*x = PollAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[55]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAnswer) ProtoMessage() {}

func (x *PollAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[55]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAnswer.ProtoReflect.Descriptor instead.
func (*PollAnswer) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{55}
}

type ChatMemberUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatMemberUpdated) Reset() {
	*x = ChatMemberUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[56]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberUpdated) ProtoMessage() {}

func (x *ChatMemberUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[56]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberUpdated.ProtoReflect.Descriptor instead.
func (*ChatMemberUpdated) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{56}
}

type ChatJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatJoinRequest) Reset() {
	*x = ChatJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[57]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatJoinRequest) ProtoMessage() {}

func (x *ChatJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[57]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatJoinRequest.ProtoReflect.Descriptor instead.
func (*ChatJoinRequest) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{57}
}

type ChatBoostUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatBoostUpdated) Reset() {
	*x = ChatBoostUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[58]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatBoostUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBoostUpdated) ProtoMessage() {}

func (x *ChatBoostUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[58]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBoostUpdated.ProtoReflect.Descriptor instead.
func (*ChatBoostUpdated) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{58}
}

type ChatBoostRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatBoostRemoved) Reset() {
	*x = ChatBoostRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[59]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatBoostRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBoostRemoved) ProtoMessage() {}

func (x *ChatBoostRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[59]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBoostRemoved.ProtoReflect.Descriptor instead.
func (*ChatBoostRemoved) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{59}
}

type InlineKeyboardMarkup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InlineKeyboardMarkup) Reset() {
	*x = InlineKeyboardMarkup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[60]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InlineKeyboardMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardMarkup) ProtoMessage() {}

func (x *InlineKeyboardMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[60]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardMarkup.ProtoReflect.Descriptor instead.
func (*InlineKeyboardMarkup) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{60}
}

type ReplyKeyboardMarkup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplyKeyboardMarkup) Reset() {
	*x = ReplyKeyboardMarkup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[61]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyKeyboardMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyKeyboardMarkup) ProtoMessage() {}

func (x *ReplyKeyboardMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[61]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyKeyboardMarkup.ProtoReflect.Descriptor instead.
func (*ReplyKeyboardMarkup) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{61}
}

type ReplyKeyboardRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplyKeyboardRemove) Reset() {
	*x = ReplyKeyboardRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[62]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyKeyboardRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyKeyboardRemove) ProtoMessage() {}

func (x *ReplyKeyboardRemove) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[62]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyKeyboardRemove.ProtoReflect.Descriptor instead.
func (*ReplyKeyboardRemove) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{62}
}

type ForceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForceReply) Reset() {
	*x = ForceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[63]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceReply) ProtoMessage() {}

func (x *ForceReply) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[63]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceReply.ProtoReflect.Descriptor instead.
func (*ForceReply) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{63}
}

// Message representing reply parameters.
type ReplyParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplyParameters) Reset() {
	*x = ReplyParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[64]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyParameters) ProtoMessage() {}

func (x *ReplyParameters) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[64]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyParameters.ProtoReflect.Descriptor instead.
func (*ReplyParameters) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{64}
}

// Message representing reply markup options.
type ReplyMarkup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Oneof is used here to represent possible types of reply markup
	//
	// Types that are assignable to Markup:
	//
	//	*ReplyMarkup_InlineKeyboard
	//	*ReplyMarkup_ReplyKeyboard
	//	*ReplyMarkup_RemoveKeyboard
	//	*ReplyMarkup_ForceReply
	Markup isReplyMarkup_Markup `protobuf_oneof:"markup"`
}

func (x *ReplyMarkup) Reset() {
	*x = ReplyMarkup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_misc_proto_msgTypes[65]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMarkup) ProtoMessage() {}

func (x *ReplyMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_misc_proto_msgTypes[65]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMarkup.ProtoReflect.Descriptor instead.
func (*ReplyMarkup) Descriptor() ([]byte, []int) {
	return file_misc_proto_rawDescGZIP(), []int{65}
}

func (m *ReplyMarkup) GetMarkup() isReplyMarkup_Markup {
	if m != nil {
		return m.Markup
	}
	return nil
}

func (x *ReplyMarkup) GetInlineKeyboard() *InlineKeyboardMarkup {
	if x, ok := x.GetMarkup().(*ReplyMarkup_InlineKeyboard); ok {
		return x.InlineKeyboard
	}
	return nil
}

func (x *ReplyMarkup) GetReplyKeyboard() *ReplyKeyboardMarkup {
	if x, ok := x.GetMarkup().(*ReplyMarkup_ReplyKeyboard); ok {
		return x.ReplyKeyboard
	}
	return nil
}

func (x *ReplyMarkup) GetRemoveKeyboard() *ReplyKeyboardRemove {
	if x, ok := x.GetMarkup().(*ReplyMarkup_RemoveKeyboard); ok {
		return x.RemoveKeyboard
	}
	return nil
}

func (x *ReplyMarkup) GetForceReply() *ForceReply {
	if x, ok := x.GetMarkup().(*ReplyMarkup_ForceReply); ok {
		return x.ForceReply
	}
	return nil
}

type isReplyMarkup_Markup interface {
	isReplyMarkup_Markup()
}

type ReplyMarkup_InlineKeyboard struct {
	InlineKeyboard *InlineKeyboardMarkup `protobuf:"bytes,1,opt,name=inline_keyboard,json=inlineKeyboard,proto3,oneof"`
}

type ReplyMarkup_ReplyKeyboard struct {
	ReplyKeyboard *ReplyKeyboardMarkup `protobuf:"bytes,2,opt,name=reply_keyboard,json=replyKeyboard,proto3,oneof"`
}

type ReplyMarkup_RemoveKeyboard struct {
	RemoveKeyboard *ReplyKeyboardRemove `protobuf:"bytes,3,opt,name=remove_keyboard,json=removeKeyboard,proto3,oneof"`
}

type ReplyMarkup_ForceReply struct {
	ForceReply *ForceReply `protobuf:"bytes,4,opt,name=force_reply,json=forceReply,proto3,oneof"`
}

func (*ReplyMarkup_InlineKeyboard) isReplyMarkup_Markup() {}

func (*ReplyMarkup_ReplyKeyboard) isReplyMarkup_Markup() {}

func (*ReplyMarkup_RemoveKeyboard) isReplyMarkup_Markup() {}

func (*ReplyMarkup_ForceReply) isReplyMarkup_Markup() {}

var File_misc_proto protoreflect.FileDescriptor

var file_misc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x0f, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x22, 0x13, 0x0a, 0x11, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x0b, 0x0a, 0x09,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x61, 0x69, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x07,
	0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x4e, 0x6f, 0x74, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x22, 0x0f, 0x0a,
	0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22,
	0x06, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x22,
	0x06, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x6c, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x65, 0x6e, 0x75, 0x65,
	0x22, 0x0a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18,
	0x4d, 0x61, 0x79, 0x62, 0x65, 0x49, 0x6e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75,
	0x6c, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x22, 0x0e,
	0x0a, 0x0c, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x19,
	0x0a, 0x17, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x69, 0x74, 0x79, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x68, 0x61,
	0x74, 0x42, 0x6f, 0x6f, 0x73, 0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x13, 0x0a,
	0x11, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x45, 0x64, 0x69, 0x74, 0x65, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x6f,
	0x72, 0x75, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64,
	0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x46, 0x6f, 0x72, 0x75, 0x6d,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x22, 0x1b, 0x0a, 0x19, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x55, 0x6e, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x69, 0x76, 0x65,
	0x61, 0x77, 0x61, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x47,
	0x69, 0x76, 0x65, 0x61, 0x77, 0x61, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x69, 0x76, 0x65, 0x61,
	0x77, 0x61, 0x79, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x69,
	0x76, 0x65, 0x61, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0x14, 0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x43, 0x68, 0x61, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x57,
	0x65, 0x62, 0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x1d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x19, 0x0a, 0x17, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x49, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x50,
	0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x0c, 0x0a, 0x0a, 0x50, 0x6f, 0x6c, 0x6c, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x13, 0x0a,
	0x11, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74, 0x42, 0x6f, 0x6f,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x68, 0x61,
	0x74, 0x42, 0x6f, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x16, 0x0a,
	0x14, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4d,
	0x61, 0x72, 0x6b, 0x75, 0x70, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4b, 0x65,
	0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x22, 0x15, 0x0a, 0x13,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x95, 0x02, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x61,
	0x72, 0x6b, 0x75, 0x70, 0x12, 0x43, 0x0a, 0x0f, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4b, 0x65, 0x79, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x42, 0x0a, 0x0f, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4b,
	0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52,
	0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12,
	0x31, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x75, 0x70, 0x42, 0x05, 0x5a, 0x03,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_misc_proto_rawDescOnce sync.Once
	file_misc_proto_rawDescData = file_misc_proto_rawDesc
)

func file_misc_proto_rawDescGZIP() []byte {
	file_misc_proto_rawDescOnce.Do(func() {
		file_misc_proto_rawDescData = protoimpl.X.CompressGZIP(file_misc_proto_rawDescData)
	})
	return file_misc_proto_rawDescData
}

var file_misc_proto_msgTypes = make([]protoimpl.MessageInfo, 66)
var file_misc_proto_goTypes = []any{
	(*MessageOrigin)(nil),                 // 0: pb.MessageOrigin
	(*ExternalReplyInfo)(nil),             // 1: pb.ExternalReplyInfo
	(*TextQuote)(nil),                     // 2: pb.TextQuote
	(*Story)(nil),                         // 3: pb.Story
	(*Animation)(nil),                     // 4: pb.Animation
	(*Audio)(nil),                         // 5: pb.Audio
	(*PaidMediaInfo)(nil),                 // 6: pb.PaidMediaInfo
	(*Sticker)(nil),                       // 7: pb.Sticker
	(*Video)(nil),                         // 8: pb.Video
	(*VideoNote)(nil),                     // 9: pb.VideoNote
	(*Voice)(nil),                         // 10: pb.Voice
	(*MessageEntity)(nil),                 // 11: pb.MessageEntity
	(*LinkPreviewOptions)(nil),            // 12: pb.LinkPreviewOptions
	(*Contact)(nil),                       // 13: pb.Contact
	(*Dice)(nil),                          // 14: pb.Dice
	(*Game)(nil),                          // 15: pb.Game
	(*Poll)(nil),                          // 16: pb.Poll
	(*Venue)(nil),                         // 17: pb.Venue
	(*Location)(nil),                      // 18: pb.Location
	(*MaybeInaccessibleMessage)(nil),      // 19: pb.MaybeInaccessibleMessage
	(*Invoice)(nil),                       // 20: pb.Invoice
	(*SuccessfulPayment)(nil),             // 21: pb.SuccessfulPayment
	(*RefundedPayment)(nil),               // 22: pb.RefundedPayment
	(*UsersShared)(nil),                   // 23: pb.UsersShared
	(*ChatShared)(nil),                    // 24: pb.ChatShared
	(*WriteAccessAllowed)(nil),            // 25: pb.WriteAccessAllowed
	(*PassportData)(nil),                  // 26: pb.PassportData
	(*ProximityAlertTriggered)(nil),       // 27: pb.ProximityAlertTriggered
	(*ChatBoostAdded)(nil),                // 28: pb.ChatBoostAdded
	(*ChatBackground)(nil),                // 29: pb.ChatBackground
	(*ForumTopicCreated)(nil),             // 30: pb.ForumTopicCreated
	(*ForumTopicEdited)(nil),              // 31: pb.ForumTopicEdited
	(*ForumTopicClosed)(nil),              // 32: pb.ForumTopicClosed
	(*ForumTopicReopened)(nil),            // 33: pb.ForumTopicReopened
	(*GeneralForumTopicHidden)(nil),       // 34: pb.GeneralForumTopicHidden
	(*GeneralForumTopicUnhidden)(nil),     // 35: pb.GeneralForumTopicUnhidden
	(*GiveawayCreated)(nil),               // 36: pb.GiveawayCreated
	(*Giveaway)(nil),                      // 37: pb.Giveaway
	(*GiveawayWinners)(nil),               // 38: pb.GiveawayWinners
	(*GiveawayCompleted)(nil),             // 39: pb.GiveawayCompleted
	(*VideoChatScheduled)(nil),            // 40: pb.VideoChatScheduled
	(*VideoChatStarted)(nil),              // 41: pb.VideoChatStarted
	(*VideoChatEnded)(nil),                // 42: pb.VideoChatEnded
	(*VideoChatParticipantsInvited)(nil),  // 43: pb.VideoChatParticipantsInvited
	(*WebAppData)(nil),                    // 44: pb.WebAppData
	(*MessageAutoDeleteTimerChanged)(nil), // 45: pb.MessageAutoDeleteTimerChanged
	(*BusinessConnection)(nil),            // 46: pb.BusinessConnection
	(*BusinessMessagesDeleted)(nil),       // 47: pb.BusinessMessagesDeleted
	(*MessageReactionUpdated)(nil),        // 48: pb.MessageReactionUpdated
	(*MessageReactionCountUpdated)(nil),   // 49: pb.MessageReactionCountUpdated
	(*InlineQuery)(nil),                   // 50: pb.InlineQuery
	(*ChosenInlineResult)(nil),            // 51: pb.ChosenInlineResult
	(*CallbackQuery)(nil),                 // 52: pb.CallbackQuery
	(*ShippingQuery)(nil),                 // 53: pb.ShippingQuery
	(*PreCheckoutQuery)(nil),              // 54: pb.PreCheckoutQuery
	(*PollAnswer)(nil),                    // 55: pb.PollAnswer
	(*ChatMemberUpdated)(nil),             // 56: pb.ChatMemberUpdated
	(*ChatJoinRequest)(nil),               // 57: pb.ChatJoinRequest
	(*ChatBoostUpdated)(nil),              // 58: pb.ChatBoostUpdated
	(*ChatBoostRemoved)(nil),              // 59: pb.ChatBoostRemoved
	(*InlineKeyboardMarkup)(nil),          // 60: pb.InlineKeyboardMarkup
	(*ReplyKeyboardMarkup)(nil),           // 61: pb.ReplyKeyboardMarkup
	(*ReplyKeyboardRemove)(nil),           // 62: pb.ReplyKeyboardRemove
	(*ForceReply)(nil),                    // 63: pb.ForceReply
	(*ReplyParameters)(nil),               // 64: pb.ReplyParameters
	(*ReplyMarkup)(nil),                   // 65: pb.ReplyMarkup
}
var file_misc_proto_depIdxs = []int32{
	60, // 0: pb.ReplyMarkup.inline_keyboard:type_name -> pb.InlineKeyboardMarkup
	61, // 1: pb.ReplyMarkup.reply_keyboard:type_name -> pb.ReplyKeyboardMarkup
	62, // 2: pb.ReplyMarkup.remove_keyboard:type_name -> pb.ReplyKeyboardRemove
	63, // 3: pb.ReplyMarkup.force_reply:type_name -> pb.ForceReply
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_misc_proto_init() }
func file_misc_proto_init() {
	if File_misc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_misc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MessageOrigin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ExternalReplyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TextQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Story); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Animation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Audio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PaidMediaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Sticker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*VideoNote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Voice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*MessageEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LinkPreviewOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Dice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Poll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*Venue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*MaybeInaccessibleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Invoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*SuccessfulPayment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*RefundedPayment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*UsersShared); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*ChatShared); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*WriteAccessAllowed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*PassportData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*ProximityAlertTriggered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*ChatBoostAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*ChatBackground); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*ForumTopicCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*ForumTopicEdited); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*ForumTopicClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*ForumTopicReopened); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*GeneralForumTopicHidden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*GeneralForumTopicUnhidden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[36].Exporter = func(v any, i int) any {
			switch v := v.(*GiveawayCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[37].Exporter = func(v any, i int) any {
			switch v := v.(*Giveaway); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[38].Exporter = func(v any, i int) any {
			switch v := v.(*GiveawayWinners); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[39].Exporter = func(v any, i int) any {
			switch v := v.(*GiveawayCompleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[40].Exporter = func(v any, i int) any {
			switch v := v.(*VideoChatScheduled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[41].Exporter = func(v any, i int) any {
			switch v := v.(*VideoChatStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[42].Exporter = func(v any, i int) any {
			switch v := v.(*VideoChatEnded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[43].Exporter = func(v any, i int) any {
			switch v := v.(*VideoChatParticipantsInvited); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[44].Exporter = func(v any, i int) any {
			switch v := v.(*WebAppData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[45].Exporter = func(v any, i int) any {
			switch v := v.(*MessageAutoDeleteTimerChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[46].Exporter = func(v any, i int) any {
			switch v := v.(*BusinessConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[47].Exporter = func(v any, i int) any {
			switch v := v.(*BusinessMessagesDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[48].Exporter = func(v any, i int) any {
			switch v := v.(*MessageReactionUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[49].Exporter = func(v any, i int) any {
			switch v := v.(*MessageReactionCountUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[50].Exporter = func(v any, i int) any {
			switch v := v.(*InlineQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[51].Exporter = func(v any, i int) any {
			switch v := v.(*ChosenInlineResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[52].Exporter = func(v any, i int) any {
			switch v := v.(*CallbackQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[53].Exporter = func(v any, i int) any {
			switch v := v.(*ShippingQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[54].Exporter = func(v any, i int) any {
			switch v := v.(*PreCheckoutQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[55].Exporter = func(v any, i int) any {
			switch v := v.(*PollAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[56].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMemberUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[57].Exporter = func(v any, i int) any {
			switch v := v.(*ChatJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[58].Exporter = func(v any, i int) any {
			switch v := v.(*ChatBoostUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[59].Exporter = func(v any, i int) any {
			switch v := v.(*ChatBoostRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[60].Exporter = func(v any, i int) any {
			switch v := v.(*InlineKeyboardMarkup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[61].Exporter = func(v any, i int) any {
			switch v := v.(*ReplyKeyboardMarkup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[62].Exporter = func(v any, i int) any {
			switch v := v.(*ReplyKeyboardRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[63].Exporter = func(v any, i int) any {
			switch v := v.(*ForceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[64].Exporter = func(v any, i int) any {
			switch v := v.(*ReplyParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_misc_proto_msgTypes[65].Exporter = func(v any, i int) any {
			switch v := v.(*ReplyMarkup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_misc_proto_msgTypes[65].OneofWrappers = []any{
		(*ReplyMarkup_InlineKeyboard)(nil),
		(*ReplyMarkup_ReplyKeyboard)(nil),
		(*ReplyMarkup_RemoveKeyboard)(nil),
		(*ReplyMarkup_ForceReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_misc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   66,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_misc_proto_goTypes,
		DependencyIndexes: file_misc_proto_depIdxs,
		MessageInfos:      file_misc_proto_msgTypes,
	}.Build()
	File_misc_proto = out.File
	file_misc_proto_rawDesc = nil
	file_misc_proto_goTypes = nil
	file_misc_proto_depIdxs = nil
}
